version: '3'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./.persistence/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  redis:
    image: redis:6.2.5-alpine
    restart: always
  web:
    image: rails_wechat
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgres://postgres:postgres@postgres/dummy_development
      SKIP_TEST_DATABASE: 'true'
  sidekiq:
    image: rails_wechat
    restart: always
    depends_on:
      - web
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
    entrypoint: bundle exec sidekiq -r test/dummy
  nginx:
    image: 1.21-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.persistence/conf.d:/etc/nginx/conf.d
      - ./.persistence/log:/var/log/nginx
      - ./.persistence/www:/var/www
