regular:
  - bars
  - bolt
  - building
  - certificate
  - check
  - chevron-right
  - credit-card
  - comments
  - door-open
  - folder
  - gears
  - globe
  - inbox
  - message
  - paper-plane
  - paperclip
  - pencil
  - qrcode
  - reply-all
  - shapes
  - user-tag
  - users
  - vial
brands:
  - amazon-pay
  - weixin