light:
  - bars
  - bolt
  - building
  - certificate
  - check
  - chevron-right
  - cloud-arrow-up
  - credit-card
  - comments
  - door-open
  - ellipsis-vertical
  - eye
  - folder
  - gear
  - gears
  - globe
  - inbox
  - magnifying-glass
  - message
  - mobile
  - paper-plane
  - paperclip
  - pencil
  - qrcode
  - reply-all
  - rotate
  - shapes
  - shield
  - trash
  - upload
  - user-tag
  - users
  - vial
brands:
  - amazon-pay
  - weixin