regular:
  - bars
  - bolt
  - building
  - certificate
  - check
  - credit-card
  - comments
  - door-open
  - gears
  - globe
  - inbox
  - message
  - paperclip
  - qrcode
  - vial
brands:
  - amazon-pay
  - weixin