name: Deploy
on:
  push:
    branches:
      - deploy
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Docker build
        run: |
          docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY:latest .
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY:latest
      - name: Docker push production
        if: ${{ github.ref == 'refs/heads/deploy' }}
        run: |
          docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/engine:latest docker.pkg.github.com/$GITHUB_REPOSITORY/engine:production
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/engine:production
