name: Deploy
on:
  push:
    branches:
      - main
      - deploy
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Docker build
        run: |
          docker build -t $GITHUB_REPOSITORY/engine:latest .
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GITHUB_REGISTRY }}
          username: ${{ secrets.GITHUB_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push latest
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push $GITHUB_REPOSITORY/engine:latest
      - name: Docker push production
        if: ${{ github.ref == 'refs/heads/deploy' }}
        run: |
          docker tag $GITHUB_REPOSITORY/engine:latest $GITHUB_REPOSITORY/engine:production
          docker push $GITHUB_REPOSITORY/engine:production
